python/routes.py
from flask import Blueprint, redirect, render_template, request, session, url_for
from .models import Content, Profiles, Users
from .profiles import logged_in_profile_data

main = Blueprint('main', __name__)

@main.route('/home')
def home():
    #So that only logged in users can view
    if 'user_id' not in session:
        return redirect(url_for('authenticator.login'))
    
    profile_data = logged_in_profile_data(['profile_id', 'profile_photo'])
    if profile_data:
        logged_in_profile_id, logged_in_profile_photo = profile_data
        return render_template('home.html', 
                               user_id=session['user_id'], 
                               logged_in_username=session['username'],
                               logged_in_profile_id=logged_in_profile_id, 
                               logged_in_profile_photo=logged_in_profile_photo)
    else:
        return render_template('home.html', user_id=session['user_id'])

@main.route('/recommended')
def recommended():
    if 'user_id' not in session:
        return redirect(url_for('authenticator.login'))

    # Displays correct profile photo when rendering page
    logged_in_profile_id, logged_in_profile_photo = logged_in_profile_data(['profile_id', 'profile_photo'])

    # Get all recommended content
    recommended_content = Content.query.all()

    # Usernames for recommended content
    user_ids = [item.user_id for item in recommended_content]
    users = Users.query.filter(Users.user_id.in_(user_ids)).all()
    username_map = {user.user_id: user.username for user in users}

    # profile details for recommended content
    profiles = Profiles.query.filter(Profiles.user_id.in_(user_ids)).all()
    profile_map = {profile.user_id: (profile.profile_id, profile.profile_photo) for profile in profiles}

    for item in recommended_content:
        item.username = username_map.get(item.user_id, 'Anonymous')
        item.profile_id, item.profile_photo = profile_map.get(item.user_id, (None, None))

    return render_template('contentFeed.html', 
                           content_items=recommended_content, 
                           user_id=session['user_id'], 
                           logged_in_username=session['username'],
                           logged_in_profile_id=logged_in_profile_id, 
                           logged_in_profile_photo=logged_in_profile_photo)

@main.route('/following')
def following():
    if 'user_id' not in session:
        return redirect(url_for('authenticator.login'))

    # Displays correct profile photo when rendering page
    logged_in_profile_id, logged_in_profile_photo = logged_in_profile_data(['profile_id', 'profile_photo'])

    # Get all recommended content
    recommended_content = Content.query.all()

    # Usernames for recommended content
    user_ids = [item.user_id for item in recommended_content]
    users = Users.query.filter(Users.user_id.in_(user_ids)).all()
    username_map = {user.user_id: user.username for user in users}

    # profile details for recommended content
    profiles = Profiles.query.filter(Profiles.user_id.in_(user_ids)).all()
    profile_map = {profile.user_id: (profile.profile_id, profile.profile_photo) for profile in profiles}

    for item in recommended_content:
        item.username = username_map.get(item.user_id, 'Anonymous')
        item.profile_id, item.profile_photo = profile_map.get(item.user_id, (None, None))

    return render_template('contentFeed.html', 
                           content_items=recommended_content, 
                           user_id=session['user_id'],
                           logged_in_username=session['username'], 
                           logged_in_profile_id=logged_in_profile_id, 
                           logged_in_profile_photo=logged_in_profile_photo)

@main.route('/personal')
def personal():
    if 'user_id' not in session:
        return redirect(url_for('authenticator.login'))

    # Displays correct profile photo when rendering page
    logged_in_profile_id, logged_in_profile_photo = logged_in_profile_data(['profile_id', 'profile_photo'])

    # Get all recommended content
    recommended_content = Content.query.all()

    # Usernames for recommended content
    user_ids = [item.user_id for item in recommended_content]
    users = Users.query.filter(Users.user_id.in_(user_ids)).all()
    username_map = {user.user_id: user.username for user in users}

    # profile details for recommended content
    profiles = Profiles.query.filter(Profiles.user_id.in_(user_ids)).all()
    profile_map = {profile.user_id: (profile.profile_id, profile.profile_photo) for profile in profiles}

    for item in recommended_content:
        item.username = username_map.get(item.user_id, 'Anonymous')
        item.profile_id, item.profile_photo = profile_map.get(item.user_id, (None, None))

    return render_template('contentFeed.html', 
                           content_items=recommended_content, 
                           user_id=session['user_id'], 
                           logged_in_username=session['username'],
                           logged_in_profile_id=logged_in_profile_id, 
                           logged_in_profile_photo=logged_in_profile_photo)

@main.route('/search', methods=['GET'])
def search():
    if 'user_id' not in session:
        return redirect(url_for('authenticator.login'))
    #Displays correct profile photo when rendering page
    logged_in_profile_id, logged_in_profile_photo = logged_in_profile_data(['profile_id', 'profile_photo'])

    keyword = request.args.get('keyword', '')
    results = Content.query.filter(Content.title.like(f'%{keyword}%')).all()

    #Usernames for results
    user_ids = [item.user_id for item in results]
    users = Users.query.filter(Users.user_id.in_(user_ids)).all()
    username_map = {user.user_id: user.username for user in users}

    #profile details for results
    profiles = Profiles.query.filter(Profiles.user_id.in_(user_ids)).all()
    profile_map = {profile.user_id: (profile.profile_id, profile.profile_photo) for profile in profiles}

    for item in results:
        item.username = username_map.get(item.user_id, 'Anonymous')
        item.profile_id, item.profile_photo = profile_map.get(item.user_id, (None, None))

    return render_template('contentFeed.html', 
                           content_items=results, 
                           user_id=session['user_id'], 
                           logged_in_username=session['username'],
                           logged_in_profile_id=logged_in_profile_id, 
                           logged_in_profile_photo=logged_in_profile_photo)

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    {% block head %}{% endblock %}
    <script src="{{ url_for('static', filename='js/reactions.js') }}"></script>
    <script src="{{ url_for('static', filename='js/comments.js') }}"></script>
    <link href="{{ url_for('static', filename='frontend/build/static/css/main.e29de497.css') }}" rel="stylesheet">
</head>
<body>
    <div class="container">
        <aside>
            <div class="profile-info">
                <a id="profileLink" href="{{ url_for('profiles.load_profile', url_profile_id=logged_in_profile_id) }}">
                    <img class="profile-image" src="{{ url_for('static', filename=logged_in_profile_photo) }}" alt="Profile Photo">
                </a>
                <p id="logged_in_username">{{logged_in_username}}</p>
            </div>
            <nav>
                <ul>
                    <li><a href="{{ url_for('main.home',page='home') }}">Home</a></li>
                    <li><a href="{{ url_for('main.recommended',page='recommended') }}">Recommended</a></li>
                    <li><a href="{{ url_for('main.following',page='following') }}">Following</a></li>
                    <li><a href="{{ url_for('main.personal',page='personal') }}">Personal</a></li>
                </ul>
            </nav>
            <div id="upload-section">
                <p>Upload content</p>
                <form id="upload-form" enctype="multipart/form-data" action="/upload" method="post">
                    <input type="text" name="title" placeholder="Enter title">
                    <input type="file" name="file">
                    <input id="upload-submit-button" type="submit" value="Upload">
                </form>
                <script src="{{ url_for('static', filename='js/upload.js') }}"></script>
                <div id="confirmation-message"></div>
            </div>
        </aside>
        <main>
            <header>
                <div class="spacer"></div>
                <form id="search-form" action="/search" method="get">
                    <input type="text" id="keyword" name="keyword" placeholder="Search...">
                    <input id="search-submit-button" type="submit" value="Search">
                </form>
                <div class="spacer"></div>
                <div id="chat-app-root"></div>
            </header>
            <div class="content">
                {% block media_content %}
                {% endblock %}
            </div>
        </main>
    </div>
    <script src="{{ url_for('static', filename='frontend/build/static/js/main.626fe4e3.js') }}"></script>
</body>
</html>

templates/contentFeed.html
{% extends "base.html" %}
{% import "content_widget.html" as content_widget %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/contentFeed.css') }}">
{% endblock %}

{% block media_content %}
    <div class="results-wrapper">
        <div id="results">
            {{ content_widget.render_content(content_items) }}
        </div>
    </div>
{% endblock %}

templates/content_widget.html
{% macro render_content(content_items) %}
    {% if content_items %}
        {% for item in content_items %}
            <div class="content-item">
                <!-- Content Display -->
                <h1>{{ item.title }}</h1>
                {% if item.content_type == "image" %}
                    <img class="raw-content" src="{{ url_for('static', filename=item.path) }}" alt="Content Image" width="560">
                {% elif item.content_type == "video" %}
                    <video width="560" height="315" controls>
                        <source class="raw-content" src="{{ url_for('static', filename=item.path) }}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                {% endif %}

                <div class="content-metadata">
                    <div class="uploader-info">
                        <a href="{{ url_for('profiles.load_profile', url_profile_id=item.profile_id) }}">
                            <img id="uploader-photo" src="{{ url_for('static', filename=item.profile_photo) }}" alt="Profile picture">
                        </a>
                        <p class="username">{{ item.username }}</p>
                    </div>

                    <!--Like/Dislike Buttons-->
                    <button class="like-button" onclick="contentReaction('{{ item.id }}', 'like')">Likes
                        <span id="like-count-{{ item.id }}" class="like-count">{{ item.likes }}</span>
                    </button>
                    <button class="dislike-button" onclick="contentReaction('{{ item.id }}', 'dislike')">Dislikes
                        <span id="dislike-count-{{ item.id }}" class="dislike-count">{{ item.dislikes }}</span>
                    </button>

                    <!--Comments-->
                    <button class="comment-button" data-content-id="{{ item.id }}" onclick="toggleCommentSection('{{ item.id }}')">Comments
                        <span class="comment-count" id="comment-count-{{ item.id }}">{{ item.comments }}</span>
                    </button>
                    <span class="view-count">{{ item.views}} Views</span>
                </div>
                <!--Hidden Comment Section for each item of content-->
                <div class="comment-section" id="comment-section-{{ item.id }}" style="display:none;">
                    <!--Add a Comment-->
                    <div class="add-comment">
                        <textarea class="comment-input" id="new-comment-{{ item.id }}" placeholder="Add a comment"></textarea>
                        <button class="post-comment" onclick="addComment('{{ item.id }}', null, document.getElementById('new-comment-{{ item.id }}').value)">Post</button>
                    </div>
                    <ul class="comment-list" id="comment-list-{{ item.id }}">
                        <!--Populated by JavaScript-->
                    </ul>
                </div>                
            </div>
        {% endfor %}
    {% else %}
        <p>No content items found.</p>
    {% endif %}
{% endmacro %}

templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
<title>Home</title>
<!-- HTML structure for the Home feed -->
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% import "content_widget.html" as content_widget %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock %}

{% block media_content %}
    <div class="results-wrapper">
        <div id="results">
            {{ content_widget.render_content(content_items) }}
        </div>
    </div>
{% endblock %}